# Generated by Django 3.2.19 on 2023-06-15 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prospects', '0002_conversion_tracker'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt_paid', models.PositiveIntegerField(default=0)),
                ('payment_mode', models.CharField(choices=[('MPESA ', 'Mpesa'), ('CHEQUE', 'Cheque'), ('BANK-TRANSACTION', 'Bank Payment')], default='Mpesa', max_length=20)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facilityname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prospects.business_prospect')),
            ],
        ),
    ]
