# Generated by Django 3.2.19 on 2023-06-15 15:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='implementation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('town', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=70)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('golive_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('no_of_days', models.IntegerField(blank=True, max_length=30)),
                ('license_due', models.DateField(default=django.utils.timezone.now)),
                ('facility_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.receipt')),
            ],
        ),
    ]
