# Generated by Django 3.2.19 on 2023-06-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_implementation_no_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementation',
            name='next_anniversary',
            field=models.DateField(blank=True, null=True),
        ),
    ]
