# Generated by Django 3.2.19 on 2023-06-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_implementation_next_anniversary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implementation',
            name='next_anniversary',
        ),
    ]
