# Generated by Django 3.2.19 on 2023-06-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_implementation_next_anniversary'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementation',
            name='implementation_report',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
