# Generated by Django 3.2.19 on 2023-06-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_receipt_amt_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='amt_paid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
