# Generated by Django 3.2.19 on 2023-06-19 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_conversion_tracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_prospect',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='business_prospect',
            name='feedback_timestamp',
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True)),
                ('feedback_timestamp', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospects.business_prospect')),
            ],
        ),
    ]
